### ISSUE TITLE
Install in Centos 7 unable to run

### ISSUE THREAD

**Issue by kennetham** [cloudfoundry-incubator/spiff#59]
How is this installed? I have downloaded the spiff source from Git, but are there examples to how should I run spiff with my cf-stub.yml?

Besides, installing GOLANG, what environment variables should I set?

Please advise.

**Comment by ematpl** [comment]
Hi, @kennetham,

What errors are you seeing when you try to run spiff, or when you try to build it from source? Building and installing spiff from source should use the same procedure as for any other Go program that uses Godeps to vendor its dependencies.

Instead of building the spiff executable yourself, you could also download the latest linux/amd64-compiled release from the [GitHub releases page](https://github.com/cloudfoundry-incubator/spiff/releases). That should run fine on CentOS 7 with a 64-bit Intel-compatible architecture.

Thanks,
Eric, CF Runtime Diego PM

**Comment by kennetham** [comment]
Hi @ematpl,

I don't have the error logs already. I managed to get it running. Somehow the GOPATH was the issue to why it didn't execute correctly.

Besides, I tried running Spiff with `cf-stub.yml` yesterday and I had a whole new error with the dynaml static IPs merging. Somehow it had to do with the network name to be set t `cf1` instead of any other name.

Thanks
